import { Product } from './types';

const perfumes: Product[] = [
  {
    name: "Victory Pulse (CR7)",
    "Price (30ml)": "PKR 2000",
    "Discounted Price (30ml)": "PKR 1699",
    "Price (50ml)": "PKR 2700",
    "Discounted Price (50ml)": "PKR 2199",
    description: "Bold energy with a confident kick",
    category: "Fresh & Sporty",
    image: "/product_imgs/front-view-men-cologne-light-grey-background-with-free-space.jpg",
    slug: "victory-pulse-cr7",
  },
  {
    name: "Fuel Rush (J. Janan Sports)",
    "Price (30ml)": "PKR 1900",
    "Discounted Price (30ml)": "PKR 1599",
    "Price (50ml)": "PKR 2600",
    "Discounted Price (50ml)": "PKR 2099",
    description: "Explosive freshness for endless drive",
    category: "Fresh & Sporty",
    image: "/product_imgs/front-view-transparent-bottle-fragrance-isolated-white-wall.jpg",
    slug: "fuel-rush-j-janan-sports",
  },
  {
    name: "Silken Whisper (White Musk)",
    "Price (30ml)": "PKR 1800",
    "Discounted Price (30ml)": "PKR 1499",
    "Price (50ml)": "PKR 2500",
    "Discounted Price (50ml)": "PKR 1999",
    description: "Pure elegance wrapped in softness",
    category: "Floral & Sweet",
    image: "/product_imgs/feminine-perfume-glass-bottle-powder-textured.jpg",
    slug: "silken-whisper-white-musk",
  },
  {
    name: "Bliss Bloom (Bombshell)",
    "Price (30ml)": "PKR 2100",
    "Discounted Price (30ml)": "PKR 1749",
    "Price (50ml)": "PKR 2800",
    "Discounted Price (50ml)": "PKR 2299",
    description: "A radiant floral explosion of joy",
    category: "Floral & Sweet",
    image: "/product_imgs/front-view-perfume-bottle-glass-model-red-color-with-gold-plastic-cover.jpg",
    slug: "bliss-bloom-bombshell",
  },
  {
    name: "Midnight Steel (Dior Sauvage)",
    "Price (30ml)": "PKR 2200",
    "Discounted Price (30ml)": "PKR 1799",
    "Price (50ml)": "PKR 3000",
    "Discounted Price (50ml)": "PKR 2399",
    description: "Rugged yet refined, like the night sky",
    category: "Woody & Oriental",
    image: "/product_imgs/front-view-rectangular-cologne-bottle-branch-rotten-wood-beige-background.jpg",
    slug: "midnight-steel-dior-sauvage",
  },
  {
    name: "Bloom Riot (Gucci Bloom)",
    "Price (30ml)": "PKR 2200",
    "Discounted Price (30ml)": "PKR 1799",
    "Price (50ml)": "PKR 3000",
    "Discounted Price (50ml)": "PKR 2399",
    description: "A garden captured in a bottle",
    category: "Floral & Sweet",
    image: "/product_imgs/long-black-perfume-bottle-decorated-with-cranberry-bergamot-leaves (1).jpg",
    slug: "bloom-riot-gucci-bloom",
  },
  {
    name: "Essence Reign (Creed Aventus)",
    "Price (30ml)": "PKR 2300",
    "Discounted Price (30ml)": "PKR 1899",
    "Price (50ml)": "PKR 3200",
    "Discounted Price (50ml)": "PKR 2499",
    description: "Power, success, and legacy in scent",
    category: "Luxury & Signature",
    image: "/product_imgs/perfume-bottle-natural-background-tree-bark-stones-top-view-beauty-fashion-perfume-template.jpg",
    slug: "essence-reign-creed-aventus",
  },
  {
    name: "Royal Ember (Majestic Oud)",
    "Price (30ml)": "PKR 2300",
    "Discounted Price (30ml)": "PKR 1899",
    "Price (50ml)": "PKR 3200",
    "Discounted Price (50ml)": "PKR 2499",
    description: "Smoky opulence wrapped in warmth",
    category: "Woody & Oriental",
    image: "/product_imgs/liquor-beautiful-glass-bottle.jpg",
    slug: "royal-ember-majestic-oud",
  },
  {
    name: "Pure Veil (White Oud)",
    "Price (30ml)": "PKR 2200",
    "Discounted Price (30ml)": "PKR 1899",
    "Price (50ml)": "PKR 3000",
    "Discounted Price (50ml)": "PKR 2399",
    description: "Subtle yet rich veil of oud",
    category: "Woody & Oriental",
    image: "/product_imgs/still-life-beauty-products-based-regenerative-agriculture.jpg",
    slug: "pure-veil-white-oud",
  },
  {
    name: "Desert Brew (Khamra Qehwa)",
    "Price (30ml)": "PKR 2300",
    "Discounted Price (30ml)": "PKR 1899",
    "Price (50ml)": "PKR 3200",
    "Discounted Price (50ml)": "PKR 2499",
    description: "Exotic warmth of spiced coffee",
    category: "Gourmand & Warm",
    image: "/product_imgs/ecofriendly-beauty-product (1).jpg",
    slug: "desert-brew-khamra-qehwa",
  },
  {
    name: "Velvet Rush (9pm)",
    "Price (30ml)": "PKR 2100",
    "Discounted Price (30ml)": "PKR 1749",
    "Price (50ml)": "PKR 2800",
    "Discounted Price (50ml)": "PKR 2299",
    description: "Night-time allure with a sweet rush",
    category: "Gourmand & Warm",
    image: "/product_imgs/minimal-beauty-products-composition.jpg",
    slug: "velvet-rush-9pm",
  },
  {
    name: "Mocha Muse (Romantic Coffee)",
    "Price (30ml)": "PKR 2100",
    "Discounted Price (30ml)": "PKR 1749",
    "Price (50ml)": "PKR 2800",
    "Discounted Price (50ml)": "PKR 2299",
    description: "A cozy blend of romance and coffee",
    category: "Gourmand & Warm",
    image: "/product_imgs/top-view-valentines-day-present-fragnance-inside-package-blue-surface-color-marriage-couple-gift-perfume.jpg",
    slug: "mocha-muse-romantic-coffee",
  },
  {
    name: "Aqua Dusk (Hawas Rasasi)",
    "Price (30ml)": "PKR 2000",
    "Discounted Price (30ml)": "PKR 1699",
    "Price (50ml)": "PKR 2700",
    "Discounted Price (50ml)": "PKR 2199",
    description: "Fresh aquatic waves under twilight",
    category: "Fresh & Sporty",
    image: "/product_imgs/aqua-dusk-hawas-rasasi.png",
    slug: "aqua-dusk-hawas-rasasi",
  },
  {
    name: "Urban Vibe (U.D.V)",
    "Price (30ml)": "PKR 1900",
    "Discounted Price (30ml)": "PKR 1549",
    "Price (50ml)": "PKR 2600",
    "Discounted Price (50ml)": "PKR 2049",
    description: "City lights bottled in a bold rhythm",
    category: "Fresh & Sporty",
    image: "/product_imgs/urban-vibe-udv.png",
    slug: "urban-vibe-udv",
  },
  {
    name: "Radiant Petal (Bright Crystal)",
    "Price (30ml)": "PKR 2200",
    "Discounted Price (30ml)": "PKR 1799",
    "Price (50ml)": "PKR 3000",
    "Discounted Price (50ml)": "PKR 2399",
    description: "A sparkling bouquet for radiant souls",
    category: "Floral & Sweet",
    image: "/product_imgs/radiant-petal-bright-crystal.jpeg",
    slug: "radiant-petal-bright-crystal",
  },
  {
    name: "Azure Flame (Bleu de Chanel)",
    "Price (30ml)": "PKR 2300",
    "Discounted Price (30ml)": "PKR 1899",
    "Price (50ml)": "PKR 3200",
    "Discounted Price (50ml)": "PKR 2499",
    description: "Depth and elegance in a blue aura",
    category: "Luxury & Signature",
    image: "/product_imgs/azure-flame-bleu-de-chanel.jpeg",
    slug: "azure-flame-bleu-de-chanel",
  },
  {
    name: "Scarlet Mirage (Baccarat Rouge 540)",
    "Price (30ml)": "PKR 2300",
    "Discounted Price (30ml)": "PKR 1899",
    "Price (50ml)": "PKR 3200",
    "Discounted Price (50ml)": "PKR 2499",
    description: "Radiant amber and airy florals collide",
    category: "Luxury & Signature",
    image: "/product_imgs/scarlet-mirage-baccarat-rouge-540.jpeg",
    slug: "scarlet-mirage-baccarat-rouge-540",
  },
  {
    name: "Petal Reverie (Gucci Flora)",
    "Price (30ml)": "PKR 2200",
    "Discounted Price (30ml)": "PKR 1799",
    "Price (50ml)": "PKR 3000",
    "Discounted Price (50ml)": "PKR 2399",
    description: "A floral fantasy of elegance",
    category: "Floral & Sweet",
    image: "/product_imgs/petal-reverie-gucci-flora.png",
    slug: "petal-reverie-gucci-flora",
  },
  {
    name: "Shadow Resin (Oud Wood)",
    "Price (30ml)": "PKR 2300",
    "Discounted Price (30ml)": "PKR 1899",
    "Price (50ml)": "PKR 3200",
    "Discounted Price (50ml)": "PKR 2499",
    description: "Darkness refined",
    category: "Woody & Oriental",
    image: "/product_imgs/shadow-resin-oud-wood.png",
    slug: "shadow-resin-oud-wood",
  },
];

export default perfumes;
